window.esdocSearchIndex = [
  [
    "redux-idle-monitor/lib/constants.js~action_prefix",
    "variable/index.html#static-variable-ACTION_PREFIX",
    "<span>ACTION_PREFIX</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/constants.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/constants.js~activity_blueprint",
    "variable/index.html#static-variable-ACTIVITY_BLUEPRINT",
    "<span>ACTIVITY_BLUEPRINT</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/constants.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/constants.js~activity_detection_blueprint",
    "variable/index.html#static-variable-ACTIVITY_DETECTION_BLUEPRINT",
    "<span>ACTIVITY_DETECTION_BLUEPRINT</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/constants.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/constants.js~idlestatus_active",
    "variable/index.html#static-variable-IDLESTATUS_ACTIVE",
    "<span>IDLESTATUS_ACTIVE</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/constants.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/constants.js~is_dev",
    "variable/index.html#static-variable-IS_DEV",
    "<span>IS_DEV</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/constants.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/constants.js~last_idle_status_blueprint",
    "variable/index.html#static-variable-LAST_IDLE_STATUS_BLUEPRINT",
    "<span>LAST_IDLE_STATUS_BLUEPRINT</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/constants.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/constants.js~lib_name",
    "variable/index.html#static-variable-LIB_NAME",
    "<span>LIB_NAME</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/constants.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/constants.js~next_idle_status_blueprint",
    "variable/index.html#static-variable-NEXT_IDLE_STATUS_BLUEPRINT",
    "<span>NEXT_IDLE_STATUS_BLUEPRINT</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/constants.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/constants.js~reset_blueprint",
    "variable/index.html#static-variable-RESET_BLUEPRINT",
    "<span>RESET_BLUEPRINT</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/constants.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/constants.js~root_state_key",
    "variable/index.html#static-variable-ROOT_STATE_KEY",
    "<span>ROOT_STATE_KEY</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/constants.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/constants.js~start_blueprint",
    "variable/index.html#static-variable-START_BLUEPRINT",
    "<span>START_BLUEPRINT</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/constants.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/constants.js~stop_blueprint",
    "variable/index.html#static-variable-STOP_BLUEPRINT",
    "<span>STOP_BLUEPRINT</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/constants.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/blueprints.js~activityblueprint",
    "variable/index.html#static-variable-activityBlueprint",
    "<span>activityBlueprint</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/blueprints.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/blueprints.js~activitydetectionblueprint",
    "variable/index.html#static-variable-activityDetectionBlueprint",
    "<span>activityDetectionBlueprint</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/blueprints.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor~configure",
    "function/index.html#static-function-configure",
    "<span>configure</span> <span class=\"search-result-import-path\">redux-idle-monitor</span>",
    "function"
  ],
  [
    "redux-idle-monitor/lib/middleware.js~configuremiddleware",
    "function/index.html#static-function-configureMiddleware",
    "<span>configureMiddleware</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/middleware.js</span>",
    "function"
  ],
  [
    "redux-idle-monitor/lib/reducer.js~configurereducer",
    "function/index.html#static-function-configureReducer",
    "<span>configureReducer</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/reducer.js</span>",
    "function"
  ],
  [
    "redux-idle-monitor/lib/detection.js~configurestartdetection",
    "variable/index.html#static-variable-configureStartDetection",
    "<span>configureStartDetection</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/detection.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/multiplexer.js~configurestoremultiplexer",
    "variable/index.html#static-variable-configureStoreMultiplexer",
    "<span>configureStoreMultiplexer</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/multiplexer.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/context.js~createcontext",
    "function/index.html#static-function-createContext",
    "<span>createContext</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/context.js</span>",
    "function"
  ],
  [
    "redux-idle-monitor/lib/middleware.js~createmiddleware",
    "variable/index.html#static-variable-createMiddleware",
    "<span>createMiddleware</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/middleware.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/reducer.js~createreducer",
    "variable/index.html#static-variable-createReducer",
    "<span>createReducer</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/reducer.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/actions.js~createstartdetection",
    "variable/index.html#static-variable-createStartDetection",
    "<span>createStartDetection</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/actions.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/defaults.js~getactiveevents",
    "variable/index.html#static-variable-getActiveEvents",
    "<span>getActiveEvents</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/defaults.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/defaults.js~getlevel",
    "variable/index.html#static-variable-getLevel",
    "<span>getLevel</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/defaults.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/detection.js~getlocalactive",
    "variable/index.html#static-variable-getLocalActive",
    "<span>getLocalActive</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/detection.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/states.js~getnextidlestatusin",
    "variable/index.html#static-variable-getNextIdleStatusIn",
    "<span>getNextIdleStatusIn</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/states.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/defaults.js~getthresholds",
    "variable/index.html#static-variable-getThresholds",
    "<span>getThresholds</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/defaults.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/defaults.js~gettimestamp",
    "variable/index.html#static-variable-getTimeStamp",
    "<span>getTimeStamp</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/defaults.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/defaults.js~getusefaststate",
    "variable/index.html#static-variable-getUseFastState",
    "<span>getUseFastState</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/defaults.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/defaults.js~getuselocalstate",
    "variable/index.html#static-variable-getUseLocalState",
    "<span>getUseLocalState</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/defaults.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/defaults.js~getusewebrtcstate",
    "variable/index.html#static-variable-getUseWebRTCState",
    "<span>getUseWebRTCState</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/defaults.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/defaults.js~getusewebsocketsstate",
    "variable/index.html#static-variable-getUseWebSocketsState",
    "<span>getUseWebSocketsState</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/defaults.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/blueprints.js~lastidlestatusblueprint",
    "variable/index.html#static-variable-lastIdleStatusBlueprint",
    "<span>lastIdleStatusBlueprint</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/blueprints.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/blueprints.js~nextidlestatusblueprint",
    "variable/index.html#static-variable-nextIdleStatusBlueprint",
    "<span>nextIdleStatusBlueprint</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/blueprints.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/blueprints.js~publicblueprints",
    "variable/index.html#static-variable-publicBlueprints",
    "<span>publicBlueprints</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/blueprints.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/blueprints.js~resetblueprint",
    "variable/index.html#static-variable-resetBlueprint",
    "<span>resetBlueprint</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/blueprints.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/detection.js~setlocalactive",
    "variable/index.html#static-variable-setLocalActive",
    "<span>setLocalActive</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/detection.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/detection.js~setlocalidle",
    "variable/index.html#static-variable-setLocalIdle",
    "<span>setLocalIdle</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/detection.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/detection.js~setlocalinit",
    "variable/index.html#static-variable-setLocalInit",
    "<span>setLocalInit</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/detection.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/blueprints.js~startblueprint",
    "variable/index.html#static-variable-startBlueprint",
    "<span>startBlueprint</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/blueprints.js</span>",
    "variable"
  ],
  [
    "redux-idle-monitor/lib/blueprints.js~stopblueprint",
    "variable/index.html#static-variable-stopBlueprint",
    "<span>stopBlueprint</span> <span class=\"search-result-import-path\">redux-idle-monitor/lib/blueprints.js</span>",
    "variable"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib/actions.js",
    "file/lib/actions.js.html",
    "lib/actions.js",
    "file"
  ],
  [
    "lib/blueprints.js",
    "file/lib/blueprints.js.html",
    "lib/blueprints.js",
    "file"
  ],
  [
    "lib/constants.js",
    "file/lib/constants.js.html",
    "lib/constants.js",
    "file"
  ],
  [
    "lib/context.js",
    "file/lib/context.js.html",
    "lib/context.js",
    "file"
  ],
  [
    "lib/defaults.js",
    "file/lib/defaults.js.html",
    "lib/defaults.js",
    "file"
  ],
  [
    "lib/detection.js",
    "file/lib/detection.js.html",
    "lib/detection.js",
    "file"
  ],
  [
    "lib/index.js",
    "file/lib/index.js.html",
    "lib/index.js",
    "file"
  ],
  [
    "lib/middleware.js",
    "file/lib/middleware.js.html",
    "lib/middleware.js",
    "file"
  ],
  [
    "lib/multiplexer.js",
    "file/lib/multiplexer.js.html",
    "lib/multiplexer.js",
    "file"
  ],
  [
    "lib/reducer.js",
    "file/lib/reducer.js.html",
    "lib/reducer.js",
    "file"
  ],
  [
    "lib/states.js",
    "file/lib/states.js.html",
    "lib/states.js",
    "file"
  ]
]